#!/usr/bin/env bash
# A Bash script that displays:
# The content of the current directory, in a list format
# Where only the part of the name after the first dash is displayed
# It uses the for loop
for i in *; do echo "$i" | cut -d '-' -f 2- ; done
